# vim: set ft=i3config ts=4 sw=4 sts=4 expandtab :

#
# 0. Variables (Mod, fonts, etc)
#

# Default modifier (Alt)
set $mod Mod1

# System / Lock variables ($mod + Ctrl + Del)
set $Locker i3lock -e -f -t -i ~/Pictures/Backgrounds/Locked/locks.png && sleep 1
set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown

# Color variables
set $col-bg-active     #082d68
set $col-bg-inactive   #08111e
set $col-bg-urgent     #e53935
set $col-text-active   #ffffff
set $col-text-inactive #999999
set $col-indicator     #2f343f

# Outputs
set $screen_primary "primary"
set $screen_displayport1 "DP-1"
set $screen_hdmi1 "HDMI-1"

# Workspace names
# Icons: https://nerdfonts.com/#cheat-sheet
set $ws1 "1:  Work"
set $ws2 "2:  Web"
set $ws3 "3: 󱐏 GPT"
set $ws4 "4: 󱃖 Code"
set $ws5 "5:  Term"
set $ws6 "6:  SSH"
set $ws7 "7:  Remote"
set $ws8 "8:  Misc"
set $ws9 "9:  Fun"
set $ws10 "0: 󰑈 TV"

