# vim: set ft=i3config ts=4 sw=4 sts=4 expandtab :

#
# 1. Outputs (monitors, workspaces to outputs)
#

# Organize workspaces between multiple monitors
workspace $ws1 output primary
workspace $ws2 output HDMI-1 primary
workspace $ws6 output primary

