# vim: set ft=i3config ts=4 sw=4 sts=4 expandtab :

#
# 1. Outputs (monitors, workspaces to outputs)
#

# Organize workspaces between multiple monitors
workspace $ws1 output $screen_primary
workspace $ws2 output $screen_displayport1 $screen_primary
workspace $ws3 output $screen_primary
workspace $ws4 output $screen_displayport1 $screen_primary
workspace $ws5 output $screen_primary
workspace $ws6 output $screen_displayport1 $screen_primary
workspace $ws7 output $screen_primary
workspace $ws8 output $screen_displayport1 $screen_primary
workspace $ws9 output $screen_primary
workspace $ws10 output $screen_hdmi1 $screen_displayport1

