# vim: set ft=i3config ts=4 sw=4 sts=4 expandtab :

#
# 4. Rules (assignments, for_window)
#

# title icons
for_window [all] title_window_icon on padding 3px

# popups
for_window [window_role="pop-up"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="app"] floating enable
for_window [window_role="page-info"] floating enable
for_window [window_role="Preferences"] floating enable

# Unresponsive pages in Google Chrome
for_window [title="Pages Unresponsive"] floating enable

# float programs(find the programs'names in "/usr/share/applictions")
for_window [class="Shutter"] floating enable
for_window [class="Gimp"] floating enable
for_window [class="Nm-connection-editor" instance="nm-connection-editor"] floating enable

# Find the class with: xprop | grep -i class
assign [class="Google-chrome"] $ws2
assign [class="Slack"] $ws2
assign [class="Telegram"] $ws2

