# vim: set ft=i3config ts=4 sw=4 sts=4 expandtab :

#
# 5. Startup (exec / exec_always)
#

# US/RU keyboard layouts (switch with Right Ctrl)
exec_always --no-startup-id "setxkbmap -model pc105 -layout us,ru -variant ,legacy -option grp:rctrl_toggle"
# Set background image
exec_always --no-startup-id feh --bg-scale ~/Pictures/Backgrounds/alleotech.png

# Start up MATE stuff
exec --no-startup-id mate-settings-daemon
exec --no-startup-id mate-power-manager
exec --no-startup-id blueman-applet
exec --no-startup-id nm-applet

# Load layouts
exec --no-startup-id i3-msg "workspace $ws2; append_layout ~/.config/i3/layouts/ws2.json"

# Start my applications (after layout is loaded)
exec --no-startup-id /usr/bin/google-chrome-stable
exec --no-startup-id /usr/bin/slack
exec --no-startup-id /usr/bin/Telegram -autostart
