---
extends: default

ignore: |
  roles/remote/

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  line-length: disable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "yes"
      - "no"
    check-keys: false
