# This playbook takes care of the base things,
# like bash, vim, and git
---
- name: Base setup
  hosts: localhost
  pre_tasks:

    - name: Install base packages
      include_role:
        name: tools
        tasks_from: rpm
      vars:
        rpms: "{{ base_packages }}"

    - name: Setup base /home folder
      include_role:
        name: tools
        tasks_from: file
      vars:
        files_src: "home/base/"
        files_dst: "/home/leonid"

    - name: Get Vim plugins
      include_role:
        name: tools
        tasks_from: git
      vars:
        git_repos: "{{ vim_plugins }}"

