---
# This task copies a given list of files and directories

- name: Ensure rsync is installed
  become: true
  dnf:
    name: rsync
    state: present

- name: Sync files and directories (rsync)
  become: false
  ansible.posix.synchronize:
    src: "{{ files_src }}/"
    dest: "{{ files_dst }}/"
    recursive: true
    archive: true
    delete: false
    times: true
    perms: true
    checksum: true
    rsync_opts: "{{ files_rsync_opts | default([]) }}"
  register: sync_result
  changed_when: sync_result.changed
