# This task copies a given list of files and directories
# For more information, see:
# - http://docs.ansible.com/ansible/copy_module.html
- name: Copying files and directories
  copy:
    src: "{{ files_src }}"
    dest: "{{ files_dst }}"
    backup: yes
    force: yes
