---
# This task copies a given list of files and directories
- name: Sync files and directories (rsync)
  become: false
  ansible.posix.synchronize:
    src: "{{ files_src }}/"
    dest: "{{ files_dst }}/"
    recursive: true
    archive: true
    delete: false
    times: true
    perms: true
    checksum: true
  register: sync_result
  changed_when: "'<<CHANGED>>' in (sync_result.stdout | default(''))"
