# This task manages a list of given git repositories
# For more information, see:
# - http://docs.ansible.com/ansible/git_module.html
- name: Managing git repositories
  git: "{{ item }}"
  with_items: "{{ git_repos }}"
  tags:
    - network
