---
# This task manages a list of given git repositories
- name: Managing git repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.get('version', omit) }}"
    update: "{{ item.get('update', omit) }}"
    force: "{{ item.get('force', omit) }}"
    accept_hostkey: "{{ item.get('accept_hostkey', omit) }}"
  loop: "{{ git_repos }}"
  tags:
    - network
