# ~/.config/i3/i3blocks.conf
command=$HOME/.config/i3/i3blocks/scripts/$BLOCK_NAME
separator_block_width=3
markup=pango
interval=1

[load]
interval=2

[memory]
interval=3

[disk_root]
interval=30

[net]
interval=5

[battery]
interval=10

[volume]
#interval=once
interval=5
signal=10

[tztime_moscow]
command=$HOME/.config/i3/i3blocks/scripts/tztime
interval=10
TZONE=Europe/Moscow
LABEL=MSK
FMT=+%H:%M

[tztime_cyprus]
command=$HOME/.config/i3/i3blocks/scripts/tztime
interval=10
TZONE=Asia/Nicosia
LABEL=CYP
