"
" Plugins
"

" Load all bundles via Pathogen vim plugin
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Change mapleader to ,
let mapleader = ","

" JavaScript and HTML indentation plugin settings
let html_indent_inctags = "html,body,head,tbody"
let html_indent_script1 = "inc"
let html_indent_style1 = "inc"

" Open NERDTree if no files were specified for vim startup
autocmd vimenter * if !argc() | NERDTree | endif

" Disable PHP coding style check with Syntastic
let syntastic_phpcs_disable = 1

" Syntax highlighting in PHP files
let php_sql_query=0
let php_parent_error_close=1
let php_parent_error_open=1
let php_htmlInStrings=0
let php_noShortTags=1
let php_folding=0

"
" Options : basic
"

syntax on					" switch on syntax highlighting
filetype plugin on
filetype indent on

set t_Co=256				" Must be BEFORE the colorscheme

"
" Options : GUI
"
if has("gui_running")
	" GUI options {{{
	set guifont=Fixedsys\ Excelsior\ 3.01\ 12
	set guioptions-=m " No menu
	set guioptions-=T " No toolbar
	set guioptions+=c " Use console dialogs where possible
	set guioptions+=lrb " Enable left, right, and bottom scrollbars
	set guioptions-=lrb " Disable left, right, and bottom scrollbars (retarded, but has to be set first)
	colorscheme wombat256mod
else
	colorscheme wombat256mod
endif


" 
" Options : misc
"

set autowrite				" saves unwritten buffers
set bg=dark					" use colors for the dark background
set bs=2					" backspace over everything in insert mode
set complete-=k				" Do not complete from dictionaries
set encoding=utf-8			" Set encoding
set formatoptions=croq
set history=50				" keep last 50 commands
set laststatus=2			" always display the status line
set matchtime=5				" Show match for half a second
set mouse=a					" Mouse support
set nobackup				" do not create backup files
set nowrap					" No line wrapping
set number 					" Set line numbering
set numberwidth=4			" Number of columns in line numbering
set ruler					" show cursor position in the file
set showcmd					" show command autocompletion
set showmatch				" Show matching opening bracket
set statusline=%F%m%r%h%w\ [EOL=%{&ff}]\ [TYPE=%Y]\ [ENC=%{(&fenc==\"\"?&enc:&fenc)}]\ %=[POS=%04l,%04v]\ [LEN=%L][%p%%]
set title titlestring=vim\ -\ %F\ %h
set visualbell				" Don't beep me, you beep!
set wildmenu				" show autocompetion in status menu
set wrapmargin=1			" margin from the right to show wrapping

" 
" Options : tabulation 
"

set autoindent				" automatic indenting of new lines
set shiftwidth=4			" indent level
set smartindent				" get smart indenting for program code-like texts
set tabstop=4				" tabs are 4 characters long
set wildchar=<tab>			" Complete filenames with Tab

" 
" Options : searching 
"

set ignorecase				" ignore case
set incsearch				" incremental search (search while pattern is typed)
set nohlsearch				" do not highlight search patterns
set smartcase				" case-insensitive searching until pattern is in lower case
set wrapscan				" wrap search around the end of file


" 
" Shortcuts
"
map <F3> :NERDTreeToggle<CR>
map <F4> :q<CR>
map <F5> :SyntasticCheck<CR>
map <F9> :TagbarToggle<CR>
map <F10> :wq<CR>

imap <C-o> <ESC>:set paste<CR>:call PhpDoc()<CR>:set nopaste<CR>

" exit to normal mode with 'jj'
inoremap jj <ESC>
