backend = "glx";
vsync = true;
use-damage = true;

# Keep fullscreen apps from being forced through the compositor when possible
unredir-if-possible = true;

# Sensible defaults
detect-client-opacity = true;
detect-rounded-corners = true;

#################################
# Shadows
#################################

shadow = true;
shadow-radius = 12;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.75;

# Don’t shadow bars/launchers/notifications
# Don’t shadow tiled windows (common in i3)
shadow-exclude = [
  "class_g = 'i3bar'",
  "class_g = 'Polybar'",
  "class_g = 'xmobar'",
  "class_g = 'dmenu'",
  "class_g = 'Rofi'",
  "name = 'Notification'",
  "_GTK_FRAME_EXTENTS",
  "_NET_WM_STATE *= '_NET_WM_STATE_TILED'"
];

#################################
# Fading
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

#################################
# Transparency
#################################

inactive-opacity = 0.95;
active-opacity = 1.0;
frame-opacity = 1.0;
opacity-rule = [
  "95:class_g = 'Slack'",
  "95:class_g = 'Telegram'",
  "99:class_g = 'Google-chrome'",
  "100:class_g = 'MPlayer'",
];

#################################
# Window-type rules
#################################

wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.95; };
  dock    = { shadow = false; };
  dnd     = { shadow = false; };
  popup_menu    = { opacity = 0.95; };
  dropdown_menu = { opacity = 0.95; };
};

