"
" Plugins
"

" Load all bundles via Pathogen vim plugin
call pathogen#infect()
call pathogen#helptags()

" Change mapleader to ,
let mapleader = ","

" Syntax
"
set bg=dark					" use colors for the dark background
syntax on					" switch on syntax highlighting
syntax enable
set t_Co=256				" Must be BEFORE the colorscheme
colorscheme lucius
hi Normal           ctermfg=253             ctermbg=none cterm=none " Set transparent background

" PHP-Indenting-for-Vim plugin
" To indent 'case:' and 'default:' statements in switch() blocks: >
let g:PHP_vintage_case_default_indent = 1

" Airline theme
let g:airline_theme='powerlineish'

" Disable folding for Markdown
let g:vim_markdown_folding_disabled = 1

" JavaScript and HTML indentation plugin settings
let html_indent_inctags = "html,body,head,tbody"
let html_indent_script1 = "inc"
let html_indent_style1 = "inc"

" Open NERDTree if no files were specified for vim startup
autocmd vimenter * if !argc() | NERDTree | endif

" Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Disable PHP coding style check with Syntastic
let g:syntastic_php_checkers=['php']
let g:syntastic_phpcs_disable=1


" Syntax highlighting in PHP files
let php_sql_query=0
let php_parent_error_close=1
let php_parent_error_open=1
let php_htmlInStrings=0
let php_noShortTags=1
let php_folding=0

" EditorConfig exclude patterns
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

"
" Options : basic
"
filetype plugin on
filetype indent on
set autoread		" Reload files changed outside of Vim

" https://vimrcfu.com/snippet/68
set splitright		" Open vertical splits to the right of current window
set splitbelow		" Open horizontal splits below the current window


"
" Options : GUI
"
if has("gui_running")
	" GUI options {{{
	set guifont=Fixedsys\ Excelsior\ 3.01\ 12
	set guioptions-=m " No menu
	set guioptions-=T " No toolbar
	set guioptions+=c " Use console dialogs where possible
	set guioptions+=lrb " Enable left, right, and bottom scrollbars
	set guioptions-=lrb " Disable left, right, and bottom scrollbars (retarded, but has to be set first)
endif


"
" Options : misc
"

set autowrite				" saves unwritten buffers
set bs=2					" backspace over everything in insert mode
set complete-=k				" Do not complete from dictionaries
set encoding=utf-8			" Set encoding
set formatoptions=croq
set history=50				" keep last 50 commands
set laststatus=2			" always display the status line
set matchtime=5				" Show match for half a second
set mouse=a					" Mouse support
set nowritebackup           " do not write backup files
set nobackup				" do not create backup files
set noswapfile 				" do not create swap files
set nowrap					" No line wrapping
set number 					" Set line numbering
set numberwidth=4			" Number of columns in line numbering
set ruler					" show cursor position in the file
set showcmd					" show command autocompletion
set showmatch				" Show matching opening bracket
set statusline=%F%m%r%h%w\ [EOL=%{&ff}]\ [TYPE=%Y]\ [ENC=%{(&fenc==\"\"?&enc:&fenc)}]\ %=[POS=%04l,%04v]\ [LEN=%L][%p%%]
set title titlestring=vim\ -\ %F\ %h
set visualbell				" Don't beep me, you beep!
set wildmenu				" show autocompetion in status menu
set wrapmargin=1			" margin from the right to show wrapping

"
" Options : tabulation
"

set autoindent				" automatic indenting of new lines
set shiftwidth=4			" indent level
set smartindent				" get smart indenting for program code-like texts
set tabstop=4				" tabs are 4 characters long
set wildchar=<tab>			" Complete filenames with Tab

"
" Options : searching
"

set ignorecase				" ignore case
set incsearch				" incremental search (search while pattern is typed)
set nohlsearch				" do not highlight search patterns
set smartcase				" case-insensitive searching until pattern is in lower case
set wrapscan				" wrap search around the end of file


"
" Shortcuts
"

" Update gitgutter signs and such every 250ms instead of default 4s
set updatetime=250
" Don't show gitgutter signs in files with more than 500 changes
let g:gitgutter_max_signs = 500

" https://vimrcfu.com/snippet/19
" Maps 'K' to open vim help for the word under cursor when editing vim files.
autocmd FileType vim setlocal keywordprg=:help

" Remap keys for split window ease of use.
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-h> <C-W>h
nmap <C-l> <C-W>l

" https://vimrcfu.com/snippet/77
" Move visual block
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Move single line
nmap <C-Up> [e
nmap <C-Down> e]

" https://vimrcfu.com/snippet/14
" Don't lose visual selection when shifting, so that >>>>>>>>> works
xnoremap <BS>  <gv
xnoremap <TAB>  >gv

" https://vimrcfu.com/snippet/186
" let terminal resize scale the internal windows
autocmd VimResized * :wincmd =

" NERDComment plugin
let NERDCommentEmptyLines = 1
let NERDDefaultAlign = 'left'
let NERDCommentWholeLinesInVMode = 1
map <Leader>/ <plug>NERDCommenterToggle<CR>
imap <Leader>/ <Esc><plug>NERDCommenterToggle<CR>i

map <F3> :NERDTreeToggle<CR>
map <F4> :q<CR>
map <F9> :TagbarToggle<CR>
map <F10> :wq<CR>

imap <C-o> <ESC>:set paste<CR>:call PhpDoc()<CR>:set nopaste<CR>

" exit to normal mode with 'jj'
inoremap jj <ESC>

