# .bashrc
#
# Lots and lots of pieces were borrowed from Advanced Bash Scripting
# Guide and the rest of the Web.  Thanks to all who helped along the
# way.


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Load scripts for dotfiles/bash/bash.d directory
DIR="$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )"
if [ -d "${DIR}/bash.d" ]
then
	SCRIPTS=`ls -1 $DIR/bash.d/*.sh 2>/dev/null | sort -n`
	if [ ! -z "$SCRIPTS" ]
	then
		for SCRIPT in $SCRIPTS
		do
			source $SCRIPT
		done
	fi
fi
