---
package_state_default: "latest"

# GUI related packages to be installed on desktops
# For parameters see:
# - http://docs.ansible.com/ansible/dnf_module.html
# - http://docs.ansible.com/ansible/yum_module.html
desktop_packages:
  # Desktop
  - flatpak
  - graphviz
  - terminator
  - pcmanfm
  - keepassxc
  # MATE Desktop Manager
  - mate-screenshot
  - eom
  # i3 Window Manager
  - i3
  - i3status
  - i3lock
  - i3blocks
  - dmenu
  - feh
  - setxkbmap
  - xkbcomp
  - xkeyboard-config
  - network-manager-applet
  - alsa-utils
  - pulseaudio-utils
  - xbacklight
  - arandr
  - picom

# Desktop applications installed from Flathub
desktop_flatpaks:
  - com.slack.Slack
  - org.telegram.desktop
